# Generated by Django 4.0.1 on 2022-01-31 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposantDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vetements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('nom', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Composants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('nom', models.CharField(max_length=500)),
                ('details', models.CharField(max_length=500)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vetement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labocore.vetements')),
            ],
        ),
        migrations.CreateModel(
            name='ComposantDesignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='images')),
                ('composant_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labocore.composantdesign')),
            ],
        ),
        migrations.AddField(
            model_name='composantdesign',
            name='composant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labocore.composants'),
        ),
    ]
