# Generated by Django 4.0.1 on 2022-01-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labocore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetements',
            name='sexe',
            field=models.CharField(choices=[('feminin', 'FEMININ'), ('masculin', 'MASCULIN')], default=1, max_length=300),
            preserve_default=False,
        ),
    ]
