# Generated by Django 4.0.1 on 2022-01-31 22:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('labocore', '0002_vetements_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetementsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='images')),
                ('vetement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labocore.vetements')),
            ],
        ),
    ]
