# Generated by Django 4.0.1 on 2022-02-02 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labocore', '0006_alter_composants_auteur_alter_composants_vetement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composants',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='composants',
            name='vetement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labocore.vetements'),
        ),
    ]
